name: Prod-Pusher

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Build project
    - run: npm run build --if-present

    - uses: aws-actions/configure-aws-credentials@v1
    - name: Configure AWS Credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload build/ folder into bucket
      run: aws s3 sync build s3://stryker-valheim-dashboard
