name: Prod-Pusher

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build static site
      run: npm install && npm run-script build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync build s3://stryker-valheim-dashboard
    - name: Deploy static site to S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 sync build s3://stryker-valheim-dashboard  


