name: Prod-Pusher

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - run: npm install

    - name: Build static site
      run: npm run-script build

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync build s3://stryker-valheim-dashboard

    - name: Create invalidation in Cloudfront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }}
          --paths "*"
