name: Prod-Pusher

on:
  push:
    branches: [ master ]
    # paths-ignore:
    #   - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - run: npm install

    - name: Build static site
      run: npm run-script build
      env:
        REACT_APP_SERVER_STATUS_URL: ${{ secrets.REACT_APP_SERVER_STATUS_URL }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync build s3://${{ secrets.AWS_BUCKET_NAME }}

    - name: Create invalidation in Cloudfront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
          --paths "/*"
